import type { CaptionFontId, FontWeight } from "@/types";

/**
 * How caption fonts reach libass. libass cannot use the browser's woff2
 * variable font, so export ships static TTF instances of Inter in
 * `assets/fonts/` (generated by `scripts/build-export-fonts.mjs`; SIL OFL
 * 1.1). Each weight has its own family name, so the ASS file picks a weight
 * by family name alone. The export copies the needed files into the job's
 * temp directory and points libass at that directory — no network, no
 * system fonts, identical on every machine.
 *
 * The three `system-*` preview fonts have no bundled equivalent: export
 * renders them with Inter (a documented parity limitation, see
 * ARCHITECTURE.md §26).
 */

export function exportFontFileName(weight: FontWeight): string {
  return `Inter-W${weight}.ttf`;
}

export function exportFontFamily(weight: FontWeight): string {
  return `Inter W${weight}`;
}

/** True when the preview font can be reproduced in the export. */
export function isFontExportFaithful(fontId: CaptionFontId): boolean {
  return fontId === "inter";
}

/**
 * libass sizes a font so its full line box (ascent + descent, using the
 * font's Windows metrics) equals the requested size, whereas CSS
 * `font-size` is the em size. Measured on Inter with the FFmpeg build this
 * project uses: an ASS size of 100 renders text 0.706× as wide as CSS
 * `font-size: 100px`, so ASS sizes are CSS px × 1/0.706.
 */
export const ASS_FONT_SIZE_PER_CSS_PX = 1 / 0.706;
